DROP DATABASE IF EXISTS burger_db;

CREATE DATABASE burger_db;

USE  burger_db;


CREATE TABLE burgers (
    id int NOT NULL AUTO_INCREMENT,
    burger VARCHAR(30),
    devoured BOOLEAN DEFAULT FALSE,
    PRIMARY KEY(id),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)